[package]
name = "game-interface-contract-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.game-interface-contract]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.54.6"
default-features = false
