// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            4
// Async Callback:                       1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    token_manager
    (
        init => init
        upgrade => upgrade
        issue_token_snow => issue_token_snow
        burn_tokens => burn_tokens
        claim_tokens => claim_tokens
        getIssuedTokensInfo => get_issued_tokens_info
    )
}

multiversx_sc_wasm_adapter::async_callback! { token_manager }
