[package]
name = "token-manager-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.token-manager]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.54.2"
default-features = false
