// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            9
// Async Callback:                       1
// Total number of exported functions:  12

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    staking_contract
    (
        init => init
        upgrade => upgrade
        stake_token_winter => stake_token_winter
        issue_reward_token => issue_reward_token
        set_reward_token_local_mint_role => set_reward_token_local_mint_role
        distribute_rewards => distribute_rewards
        get_stake_info => stake_info
        get_last_reward_epoch => last_reward_epoch
        get_reward_token_id => reward_token_id
        clear_reward_token => clear_reward_token
        set_last_reward_epoch => set_last_reward_epoch
    )
}

multiversx_sc_wasm_adapter::async_callback! { staking_contract }
