// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           20
// Async Callback:                       1
// Total number of exported functions:  23

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    resource_mint_contract
    (
        init => init
        upgrade => upgrade
        stakeTokens => stake_tokens
        mintResources => mint_resources
        claimResources => claim_resources
        getStakeTokenTicker => stake_token_ticker
        getMintStakeThreshold => mint_stake_threshold
        getMintRoundsInterval => mint_rounds_interval
        getOptionMintIfClaimed => option_mint_if_claimed
        getStakeInfo => stakes_info
        getUserMintedResources => user_minted_resources
        getUserClaimedResources => user_claimed_resources
        getUserHasUnclaimedResources => user_has_unclaimed_resources
        getResourceTokenId => resource_token_id
        getContractHasLocalMintRole => contract_has_local_mint_role
        getLastResourceMintRound => last_resource_mint_round
        setMintRoundsInterval => set_mint_rounds_interval
        setStakeThreshold => set_stake_threshold
        setOptionMintIfClaimed => set_option_mint_if_claimed
        issueResourceToken => issue_resource_token
        setContractLocalMintRole => set_contract_local_mint_role
        getUserUnclaimedResources => user_unclaimed_resources
    )
}

multiversx_sc_wasm_adapter::async_callback! { resource_mint_contract }
