// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           22
// Async Callback:                       1
// Total number of exported functions:  25

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    resource_mint_contract
    (
        init => init
        upgrade => upgrade
        issueResourceToken => issue_resource_token
        setResourceTokenLocalMintRole => set_resource_token_local_mint_role
        setMintRoundsInterval => set_mint_rounds_interval
        setOptionMintIfClaimed => set_option_mint_if_claimed
        setStakeTokenTicker => set_stake_token_ticker
        setStakeThreshold => set_stake_threshold
        stakeTokens => stake_tokens
        mintResources => mint_resources
        claimResources => claim_resources
        getRound => get_round
        getUserUnclaimedResources => user_unclaimed_resources
        getMintRoundsInterval => mint_rounds_interval
        getMintStakeThreshold => mint_stake_threshold
        getStakeTokenTicker => stake_token_ticker
        getOptionMintIfClaimed => option_mint_if_claimed
        getStakeInfo => stakes_info
        getUserMintedResources => user_minted_resources
        getUserClaimedResources => user_claimed_resources
        getUserHasUnclaimedResources => user_has_unclaimed_resources
        getResourcesToMint => resources_to_mint
        getLastResourceUpdateRound => last_resource_update_round
        getResourceTokenId => resource_token_id
    )
}

multiversx_sc_wasm_adapter::async_callback! { resource_mint_contract }
