// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           13
// Async Callback:                       1
// Total number of exported functions:  16

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    tools_contract
    (
        init => init
        upgrade => upgrade
        mintShield => mint_shield
        claimShield => claim_shield
        mintSword => mint_sword
        claimSword => claim_sword
        getToolsNftCollection => tools_nft_collection
        getShieldsToMint => shields_to_mint
        getSwordsToMint => swords_to_mint
        getMintShieldSeconds => mint_shield_seconds
        getMintSwordSeconds => mint_sword_seconds
        getLastMintedNftNonce => last_minted_nft_nonce
        registerToolsCollection => register_tools_collection
        setMintShieldSeconds => set_mint_shield_seconds
        setMintSwordSeconds => set_mint_sword_seconds
    )
}

multiversx_sc_wasm_adapter::async_callback! { tools_contract }
